version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_URI=mongodb://mongo:27017/sonata-playlist
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - '28017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

networks:
  app-network:
    driver:
      bridge

volumes:
  mongo-data:
